Telzir.FaleMais/Models/CalcularPrecoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Telzir.FaleMais.Repositories;

namespace Telzir.FaleMais.Models
{
    public class CalcularPrecoViewModel
    {

        public List<SelectListItem> Planos { get; set; }

        [Range(1, 99999999999)]        
        public int Minuto { get; set; }
        
        [Required]
        [Range(1, 999)]
        [MaxLength(3)]
        [MinLength(3)]
        public string Origem { get; set; }
        
        [Required]
        [Range(1, 999)]
        [MaxLength(3)]
        [MinLength(3)]
        public string Destino { get; set; }

        public PrecoPorMinuto Preco
        {
            get
            {
                var repo = new PrecoPorMinutoRepository();
                var obj = repo.ListarPrecos().FirstOrDefault(p => p.DDD_Origem == Origem && p.DDD_Destino == Destino);
                return obj == null ? new PrecoPorMinuto() : obj;
            }
        }
        
        public Plano Plano
        {
            get
            {
                var repo = new PlanoRepository();
                var obj = Planos.FirstOrDefault(p => p.Selected);
                return obj != null ? (repo.BuscarPeloIdentificador(Int32.Parse(obj.Value))) : new Plano();
            }
        }

        public bool IsValid
        {
            get
            {
                return Preco.Id != 0 && Minuto > 0;
            }
        }

        public decimal ValorSemPlano
        {
            get
            {
                return Preco.CalcularValorPorMinuto(Minuto);
            }
        }

        public decimal ValorComPlano
        {
            get
            {
                if (Plano.Minutos > Minuto)
                {
                    return 0;
                }
                else
                {
                    var min =  Minuto - Plano.Minutos;
                    return Plano.AcrescimoDosMinutosExcedentes(Preco.CalcularValorPorMinuto(min));
                }
            }
        }
        
        public CalcularPrecoViewModel()
        {
            this.Planos = new List<SelectListItem>();
        }

        
    }
}

Telzir.FaleMais/Models/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Telzir.FaleMais.Models
{
    public class HomeViewModel
    {
        public List<Plano> Planos { get; set; }

        public List<PrecoPorMinuto> Precos { get; set; }


    }
}

Telzir.FaleMais/Models/Plano.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Telzir.FaleMais.Models
{
    public class Plano
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [MaxLength(25)]
        public string Descricao { get; set; }

        [Required]
        public int Minutos { get; set; }

        [Required]
        public decimal TaxaDeMinutosExcedentes { get; set; }

        public decimal AcrescimoDosMinutosExcedentes(decimal valor) { 
            return valor + ( this.TaxaDeMinutosExcedentes * valor);
        }

    }
}

Telzir.FaleMais/Models/PrecoPorMinuto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Telzir.FaleMais.Models
{
    public class PrecoPorMinuto
    {
        [Key]
        [Column(Order = 0)]
        public int Id { get; set; }
        [Key]
        [Column(Order = 1)]
        [MaxLength(3)]
        [MinLength(3)]
        public string DDD_Origem { get; set; }
        [Key]
        [MaxLength(3)]
        [MinLength(3)]
        [Column(Order = 2)]
        public string DDD_Destino { get; set; }
        public decimal ValorPorMinuto { get; set; }

        public decimal CalcularValorPorMinuto(int min)
        {
            return this.ValorPorMinuto * min;
        }
    }
}

Telzir.FaleMais/Controllers/CalcularPrecoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Telzir.FaleMais.Models;
using Telzir.FaleMais.Repositories;

namespace Telzir.FaleMais.Controllers
{
    public class CalcularPrecoController : Controller
    {
        public ActionResult Index()
        {
            var planoRepo = new PlanoRepository();
            var model = new CalcularPrecoViewModel();
            planoRepo.ListarPlanos().ToList().ForEach(el => model.Planos.Add(new SelectListItem()
            {
                Text = el.Descricao,
                Value = el.Id.ToString()
            }));
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(CalcularPrecoViewModel model)
        {
            var planoRepo = new PlanoRepository();
            planoRepo.ListarPlanos().ToList().ForEach(el => model.Planos.Add(new SelectListItem()
            {
                Text = el.Descricao,
                Value = el.Id.ToString()
            }));
            return View(model);
       }


	}
}

Telzir.FaleMais/Controllers/ErroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Telzir.FaleMais.Controllers
{
    public class ErroController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

Telzir.FaleMais/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Telzir.FaleMais.Models;
using Telzir.FaleMais.Repositories;

namespace Telzir.FaleMais.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var planoRepo = new PlanoRepository();
            var precoRepo = new PrecoPorMinutoRepository();
            var model = new HomeViewModel();

            model.Precos = precoRepo.ListarPrecos();
            model.Planos = planoRepo.ListarPlanos();

            return View(model);
        }

    }
}

Telzir.FaleMais/Views/CalcularPreco/Index.cshtml
@model Telzir.FaleMais.Models.CalcularPrecoViewModel
@{
    ViewBag.Title = "Simulação";
    Layout = "~/Views/Shared/_Layout.cshtml";    
}

@section Scripts{

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

}
<div class="page-header">
    <h2>Simulação</h2>
</div>

<div class="container body-content">
   
    @using (Html.BeginForm("Index", "CalcularPreco"))
    {
        <fieldset>
            <div class="form-horizontal">

                <div class="form-group">
                    <span class="control-label col-md-2">DDD Origem</span>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Origem)
                        @Html.ValidationMessageFor(model => model.Origem)
                    </div>
                </div>

                <div class="form-group">
                    <span class="control-label col-md-2">DDD Destino</span>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Destino)
                        @Html.ValidationMessageFor(model => model.Destino)
                    </div>
                </div>

                <div class="form-group">
                    <span class="control-label col-md-2">Minutos</span>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Minuto)
                        @Html.ValidationMessageFor(model => model.Minuto)
                    </div>
                </div>

                <div class="form-group">
                    <span class="control-label col-md-2">Planos</span>
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.Plano, Model.Planos)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Calcular" class="btn btn-success" />
                    </div>
                </div>

            </div>
        </fieldset>
    }

    @{
        if (Model.IsValid)
        {
            <div>
                <div class="panel panel-success" style="float: left; margin:10px">
                    <div class="panel-heading">Valor Com Plano</div>
                    <div class="panel-body">
                        <span>R$@String.Format("{0:n2}", Model.ValorComPlano)</span>
                    </div>
                </div>

                <div class="panel panel-danger" style="float: left; margin:10px">
                    <div class="panel-heading">Valor Sem Plano</div>
                    <div class="panel-body">
                        <span>R$@String.Format("{0:n2}", Model.ValorSemPlano)</span>
                    </div>
                </div>
            </div>
        }
       
    }
</div>

Telzir.FaleMais/Views/Erro/Index.cshtml
@{
    ViewBag.Title = "Erro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="hero-unit">
    <h1>Erro</h1>
    <p>Não foi possível processar sua requisição.</p>
    <p><a class="btn btn-primary btn-large" role="button" onclick="javascript:window.history.back()">Voltar</a></p>
</div>

Telzir.FaleMais/Views/Home/Index.cshtml
@model Telzir.FaleMais.Models.HomeViewModel
@{
    ViewBag.Title = "Home";
}

@section Scripts{

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")

}

<div class="jumbotron text-center">
    <p class="lead">Com o FaleMais você economiza e fala sem preocupações.</p>
</div>

<hr />

<div class="row">
    <div class="col-xs-4">
        <h2>
            <span class="glyphicon glyphicon-hand-right"></span>
           Planos
        </h2>
        <ul class="list-group">
            @foreach (var pl in @Model.Planos)
            {
                <li class="list-group-item">
                    @pl.Descricao
                </li>
            }
        </ul>

    </div>

    <div class="col-xs-4">
        <h2>
            <span class="glyphicon glyphicon-hand-right"></span>
            Faça uma simulação e veja o quanto você pode economizar
        </h2>
        <p>
            <a href="@Url.Action("Index", "CalcularPreco")" class="btn btn-success">Simulação</a>
        </p>
    </div>

    <div class="col-xs-4">
        <h2>
            <span class="glyphicon glyphicon-hand-right"></span>
           Tabela De Preços
        </h2>
        <table class="table table-hover">
            <thead>
                <tr>
                    <td>DDD Origem</td>
                    <td>DDD Destino</td>
                    <td>Preços</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var pr in @Model.Precos)
                {
                    <tr>
                        <td>@pr.DDD_Origem</td>
                        <td>@pr.DDD_Destino</td>
                        <td>R$ @pr.ValorPorMinuto</td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

Telzir.FaleMais/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - FaleMais</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FaleMais", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Telzir</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>